services:
  haproxy:
    image: haproxy:3.0-alpine
    platform: linux/amd64
    ports:
      - "9999:9999"
    volumes:
      - ./ops/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - api1
      - api2
    networks:
      - rinha
    deploy:
      resources:
        limits:
          cpus: "0.08"
          memory: "20MB"

  api1:
    image: ghcr.io/thales-maciel/helheim:240ae7e@sha256:f6b9994e224b05ad90efe550265bb1802774a30f9ce6c8a30fb1180b1236409c
    platform: linux/amd64
    environment:
      HELHEIM_INDEX: /app/data/references.bin
      HELHEIM_ENGINE: exact
    networks:
      - rinha
    deploy:
      resources:
        limits:
          cpus: "0.46"
          memory: "165MB"

  api2:
    image: ghcr.io/thales-maciel/helheim:240ae7e@sha256:f6b9994e224b05ad90efe550265bb1802774a30f9ce6c8a30fb1180b1236409c
    platform: linux/amd64
    environment:
      HELHEIM_INDEX: /app/data/references.bin
      HELHEIM_ENGINE: exact
    networks:
      - rinha
    deploy:
      resources:
        limits:
          cpus: "0.46"
          memory: "165MB"

networks:
  rinha:
    driver: bridge
