services:
  haproxy:
    image: haproxy:3.0-alpine
    platform: linux/amd64
    ports:
      - "${HELHEIM_HOST_PORT:-9999}:9999"
    volumes:
      - ./ops/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - api1
      - api2
    networks:
      - rinha
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: "20MB"

  api1:
    image: helheim:local
    platform: linux/amd64
    build:
      context: .
    environment:
      PORT: "8080"
      HELHEIM_INDEX: /app/data/references.bin
      HELHEIM_ENGINE: exact
    networks:
      - rinha
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "165MB"

  api2:
    image: helheim:local
    platform: linux/amd64
    build:
      context: .
    environment:
      PORT: "8080"
      HELHEIM_INDEX: /app/data/references.bin
      HELHEIM_ENGINE: exact
    networks:
      - rinha
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "165MB"

networks:
  rinha:
    driver: bridge
