worker_processes 1;

events {
  worker_connections 1024;
}

http {
  access_log off;
  error_log /var/log/nginx/error.log warn;

  upstream helheim_api {
    server api1:8080;
    server api2:8080;
  }

  server {
    listen 9999;

    location / {
      proxy_http_version 1.1;
      proxy_set_header Connection "";
      proxy_set_header Host $host;
      proxy_pass http://helheim_api;
    }
  }
}
